name: node_code_editor
description: Lightweight syntax highlighting and editing rules for node editors.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
